name: Deploy to OVH hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to OVH hosting
        uses: pitscher/ovh-deploy-hosting-action@v1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_port: ${{ secrets.SSH_PORT }}
          remote_path: ${{ secrets.REMOTE_PATH }}
